### ISSUE TITLE
More Exercises

### ISSUE THREAD

**Issue by aoanla** [JuliaHEP/JuliaHEP-2023#22]
We should have 2 more short exercises (one "write some not entirely trivial code in Julia" and one "do some plots or dataframes or both").

I'll have a look at this today, but if anyone has suggestions I am open to them for topics.

**Comment by aoanla** [comment]
I'd really like to have some multiple dispatch in here, but the exercises can't be *too* heavy. I'm thinking maybe:

given

nrs_\delta(x,f,f\prime) = f(x)/f\prime(x)

and some example f, f\primes (say, x^3 - 8, 3x^2 )

[that is, the delta for successive approximation with Newton-Raphson-(Simpson)]

a) work through writing the function that takes an initial value and then iterates to return an x with some \epsilon of a root 
[does iteration, conditionals, writing a function]

test appropriately!

b) write a new method for the same function, which takes a *Vector* with a single element to start at, and iterates, saving the intermediate values in the Vector (using push!). [does multiple dispatch, parametric constraints]

test appropriately

--
c) using Plots, plot:
              a) a line graph of the function we're finding the root of
              b) a scatter plot of the successive x values and their respective function values
on the same axes.
[does plot, plot! or scatter!, broadcasting - if we generate y values as f.(xs) ]

Thoughts? Not HEP enough?

**Comment by graeme-a-stewart** [comment]
I think it would be a nice exercise - we ask people to tackle a) and b) after the first teaching stint, then to do c) after the plots tutorial?

**Comment by graeme-a-stewart** [comment]
I am also working on an exercise based on DataFrames, should be finished today

**Comment by aoanla** [comment]
btw, re the guided-ness of the NRS exercises, they started out less so and then I started worrying about the time factor... so I might revise them a bit after tomorrow if we keep this around for future things.

**Comment by graeme-a-stewart** [comment]
> btw, re the guided-ness of the NRS exercises, they started out less so and then I started worrying about the time factor... so I might revise them a bit after tomorrow if we keep this around for future things.

I do agree - I'd like also to add a little bit on ML, to further build on the data frames work
