### ISSUE TITLE
Logistics of using Binder

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/JuliaHEP-2023#25]
- remember to click on the button maybe 10 minutes before the start time to make sure ssl-hep has a valid cache
- try it and include some very quick guidelines slides before/after installing local Julia guide?

**Comment by aoanla** [comment]
...what account do you need to use the Binder service? It doesn't like me using my UoG IdP apparently (I get "you are not authorized" after I log in)

**Comment by Moelf** [comment]
CERN account should work, also try ORCid

**Comment by aoanla** [comment]
Well, first I have to work out how to *clear* my current login session (since it seems to be sticky, and I can't see a "logout and try a different IdP" button).

**Comment by Moelf** [comment]
Try in a private browser session for now just to figure out what auth works I suppose

**Comment by aoanla** [comment]
So, I've tapped out of options: my University account gets me through to the JupyterHub but hits a "not authorized" page, CERN SSO just *doesn't seem to work* (it refuses to auth me, despite my double-checking that username/password works on the CERN website), and ORCid gets to the Link Cilogon "confirm your email address" step, and then fails with "unexpected error contacting your identify provider". 

Are we sure this thing works for people outside the USA?

**Comment by Moelf** [comment]
If you can get to Jupiter page you shouldn't be not authorized. Maybe give that a minute or use a less private browser. (I may have had similar issues with Firefox but now I'm fine on Firefox)

**Comment by aoanla** [comment]
I get the same thing in Firefox and Chromium [including if I turn off literally every privacy plugin I have in Chromium], so...

Do you know, is this thing using a login list, or should it just work for any account that can authenticate via an IdP?

**Comment by Moelf** [comment]
My understanding was they didn't have an allow list which was a concern for abuse at some point. Maybe now they have?

But CERN SSO should definitely work though if they have an allow list now. I will ask
