### ISSUE TITLE
Add some Mentimeter polls/quizzes?

### ISSUE THREAD

**Issue by graeme-a-stewart** [JuliaHEP/JuliaHEP-2023#27]
As we have a tough engagement issue here, with most interested people being on Zoom, I thought we could scatter a few mentimeter polls and quizzes into the tutorial.

The hope would be that by soliciting some audience feedback we'd keep people interested/awake.

**Comment by Moelf** [comment]
this would also be useful for deciding discussion priorities for many session, do you know how to set it up?

**Comment by graeme-a-stewart** [comment]
I signed up and I am playing around with it now (at least as much as I can on a weak internet connection on the train!)

**Comment by tamasgal** [comment]
Yes, Mentimeter is an excellent idea, I wanted to bring it up in the last meeting but forgot about it.

Should we collect some questions here?

**Comment by tamasgal** [comment]
I just realised that the free plan has some limitations (50 participants/month), if I understood correctly.

**Comment by aoanla** [comment]
The wording is interesting - it says you can go over the limit *in a single presentation*, after which your account blocks until you upgrade.

**Comment by tamasgal** [comment]
Yes, kind of sounds like you have only one chance to get it right ;) Btw. they only offer yearly payments, or at least that's the only option I could find...

**Comment by graeme-a-stewart** [comment]
I have done some really simple quiz questions for the first part of the tutorial tomorrow. Let's suck it and see...

If anyone else wants to use it, I suggest they sign up independently, in case it's a one-shot wonder tomorrow morning!

**Comment by graeme-a-stewart** [comment]
This was [done](https://www.menti.com/alh1ac1u7vy3) and it worked. I think it was quite successful as it's a nice pace changer and re-engager after people have been listening to a lecture for some time. Still, it definitely worked better for people in the room - these were pretty much experts, but the discussion was fun. It's just really hard in a hybrid event to engage with the remote participants as much.

Next time I would probably use it more interspersed between each of the sections (but on the day I really didn't want to break anything as were were delivering the material).
