### ISSUE TITLE
"Second version" improvements

### ISSUE THREAD

**Issue by aoanla** [JuliaHEP/JuliaHEP-2023#29]
So, now we've run it once, this is the issue for tracking any tweaks.

Things on my list:

1) make the NRS exercise less guided now we're not time-pressured as much
    * just mention that there are various ways of doing bits (like breaking out of the loop) in the top part
2) a few tweaks to ordering in my bits, and one or two grammar fixes
    * mention ! convention for functions that modify *earlier* 
    * tweak language in the do notation bit
    * maybe some additional optional advanced bits? \@code_* bits maybe [or is it just me who likes low-level tinkering?]

**Comment by aoanla** [comment]
We could just expand "Arrays" into its own notebook and cover @view,
deepcopy, and maybe a specialist subtype (Strided? Diagonal?)

**Comment by graeme-a-stewart** [comment]
There's a few things to improve for the DataFrames
- Broken comment on the cell accessor `higgs_ml[6, [:PRI_jet_num]]`
- Should have an overview of the DataFrame methods (`filter`, `select`, `combine`)
- More explicitly spell out the filter syntax `input_column => filter => output_column`
- Filter the columns earlier to just the few that we will actually work with

Also, I would fiddle with the display parameters as the output table snapshots are just too big ATM (e.g., don't really need the training rows)

**Comment by aoanla** [comment]
Also, re that discussion in the slack just now:  minor thing, but should we consolidate on one way of writing for loops (I know I like = as a heretic, but I am happy to move to in / \in ),
(also other bits of minor normalisation like that)

**Comment by Moelf** [comment]
where was the slack discussion?

**Comment by aoanla** [comment]
The one that you contributed to where someone was upset about there being more than one way to do a thing (and used for =, in, \in etc as an example)

**Comment by graeme-a-stewart** [comment]
Personally I like `in` and $\in$! OTOH people will see all of these things used, so mentioning that is useful

**Comment by Moelf** [comment]
I think the concensus is `=` is bad, use `in` or `\in`

**Comment by graeme-a-stewart** [comment]
Just looking at Philippe's talk one should definitely add how to select rows from a boolean selector derived from column values

**Comment by graeme-a-stewart** [comment]
I think with #36 and #33 this is done now. Anything else missing?
