### ISSUE TITLE
Path of CSV file used for DataFrames tutorial

### ISSUE THREAD

**Issue by amanmdesai** [JuliaHEP/JuliaHEP-2023#30]
It would be nice to mention the explicitly the path of the CSV file and also give a link to it
in the section: Loading Data from CSV;

CSV file: atlas-higgs-challenge-2014-v2-reduced.csv

**Comment by Moelf** [comment]
>higgs_ml = CSV.read(joinpath("assets", "atlas-higgs-challenge-2014-v2-reduced.csv"), DataFrame)

yeah, this line could have used `@__DIR__` macro to make it always use relative path

**Comment by amanmdesai** [comment]
Yeah that would be useful @Moelf  Thanks.

I was wondering if it is also possible to download this csv file alone from github via Julia without cloning the entire repository?

**Comment by Moelf** [comment]
yeah, you can use `download()` with the url here: https://github.com/JuliaHEP/JuliaHEP-2023/blob/631385cfd0daa0918b81905767f3a37a02fbf160/julia-intro/docs/exercises/dataframes.md#load-and-clean-up-a-dataframe

**Comment by amanmdesai** [comment]
I see. It might be useful to also mention this in the DataFrame introduction lesson: https://juliahep.github.io/JuliaHEP-2023/julia-intro-dataframes.html

**Comment by graeme-a-stewart** [comment]
Hi @amanmdesai - thanks for pointing this out, we will improve that

**Comment by amanmdesai** [comment]
Thanks
