### ISSUE TITLE
Integration with HSF Training Center + Plausible

### ISSUE THREAD

**Issue by klieret** [JuliaHEP/JuliaHEP-2023#31]
Hi @graeme-a-stewart @Moelf @aoanla @tamasgal 

Nice tutorial you have here ;)  Do you want me to point to it from the [HSF training center](https://hepsoftwarefoundation.org/training/center)? We already have a (lonely) Julia corner in there.  Should I put `stable` or `beta`?

To improve the cross-linking and viewership of our resources, we typically would then encourage the following:

1. Including a training center badge in the gh readme (like [here](https://github.com/hsf-training/hsf-training-scikit-hep-webpage))
2. Including a small callout in the tutorial that links to the center (we have [this](https://hsf-training.github.io/hsf-training-scikit-hep-webpage/) in the Jekyll-based pages, but can just use one of the Jupyterbook callouts here)
3. Consider to include the snippet for our [Plausible](https://plausible.io/) web analysis in the HTML. This is very lightweight (and GDPR/CCPA/PECR compliant), and mainly allows us to count the number of visitors per page and (to a some extend) see the previous/next page users go to

**Comment by aoanla** [comment]
As a note: we have now taught this (once) so we possibly could have it as stable - but as you will see we have an issue for a "v2" improvement, which would be nice to get done before we decide we have a "stable" version (at least from my perspective).  There's not *huge* changes but there will be changes.

**Comment by graeme-a-stewart** [comment]
Hi @klieret - you pretty much read by mind on this. Personally, after a few tweaks, I would consider it stable, but evolving as we continue to add an improve things. But I guess that's ok, right?

**Comment by klieret** [comment]
Let me know if you want access to the web analysis data. After #34 , we now just started receiving data, but it will obviously take a while until we have some real statistics.
